### ISSUE TITLE
shots.geojson

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/test#31]
I would like to know the meaning of the "rotation" parameter in the camera parameter file, or what it stands for.

<img width="699" alt="77d9213328d8ceda84cda20143e448d" src="https://github.com/OpenDroneMap/WebODM/assets/97585208/51662639-fcd8-4878-a2d2-142d8d99a990">

**Comment by maquimartinez7** [comment]
Hey! did you finally got what rotation means? I know they are the jaw, pitch and roll values of the camera orientation, but I can't find any information about the order in which they are given in the geo json file....  do you?
